(ns words.state)

(def btn-en "🇺🇸 EN")
(def btn-de "🇩🇪 DE")
(def btn-ru "🇷🇺 RU")
(def btn-pl "🇵🇱 PL")
(def btn-show-words "📖 Show my words")
(def btn-help "❓ Help")
(def btn-exercise "📝 Start exercise")
(def btn-lessons "👩‍🏫 Lessons")
(def btn-remove "🙅‍♂️ Remove word")
(def btn-cancel "🤚 Cancel")
(def btn-stop "🤚 Stop exercise")
(def btn-lang "⚙️ Change languages")
