app:
  image: clojure
  links:
    - redis
  volumes:
    - ./:/app
    - ~/.m2:/root/.m2
    - ~/.lein:/root/.lein
  env_file: .env
  working_dir: /app
  command: lein run

ring:
  image: clojure
  links:
    - redis
  volumes:
    - ./:/app
    - ~/.m2:/root/.m2
  ports:
    - "5000:5000"
  expose:
    - 5000
  env_file: .env
  working_dir: /app
  command: lein ring server-headless 5000

redis:
  image: redis

redis-cli:
  image: redis
  links:
    - redis
  command: redis-cli -h redis
